// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfiguration) DeepCopyInto(out *NodeConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Meta.DeepCopyInto(&out.Meta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfiguration.
func (in *NodeConfiguration) DeepCopy() *NodeConfiguration {
	if in == nil {
		return nil
	}
	out := new(NodeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfigurationDirectState) DeepCopyInto(out *NodeConfigurationDirectState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfigurationDirectState.
func (in *NodeConfigurationDirectState) DeepCopy() *NodeConfigurationDirectState {
	if in == nil {
		return nil
	}
	out := new(NodeConfigurationDirectState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfigurationList) DeepCopyInto(out *NodeConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Meta.DeepCopyInto(&out.Meta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfigurationList.
func (in *NodeConfigurationList) DeepCopy() *NodeConfigurationList {
	if in == nil {
		return nil
	}
	out := new(NodeConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfigurationSpec) DeepCopyInto(out *NodeConfigurationSpec) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(NodeConfigurationState)
		(*in).DeepCopyInto(*out)
	}
	out.Resources = in.Resources
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]NodeConfigurationTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfigurationSpec.
func (in *NodeConfigurationSpec) DeepCopy() *NodeConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(NodeConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfigurationState) DeepCopyInto(out *NodeConfigurationState) {
	*out = *in
	if in.CustomState != nil {
		in, out := &in.CustomState, &out.CustomState
		*out = new(NodeConfigurationDirectState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfigurationState.
func (in *NodeConfigurationState) DeepCopy() *NodeConfigurationState {
	if in == nil {
		return nil
	}
	out := new(NodeConfigurationState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfigurationTask) DeepCopyInto(out *NodeConfigurationTask) {
	*out = *in
	in.State.DeepCopyInto(&out.State)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfigurationTask.
func (in *NodeConfigurationTask) DeepCopy() *NodeConfigurationTask {
	if in == nil {
		return nil
	}
	out := new(NodeConfigurationTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResources) DeepCopyInto(out *NodeResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResources.
func (in *NodeResources) DeepCopy() *NodeResources {
	if in == nil {
		return nil
	}
	out := new(NodeResources)
	in.DeepCopyInto(out)
	return out
}
