// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: controlplane/events/node_events.proto

package events

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// This node fails, so every request times out
type NodeFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NodeFailure) Reset() {
	*x = NodeFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_events_node_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeFailure) ProtoMessage() {}

func (x *NodeFailure) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_events_node_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeFailure.ProtoReflect.Descriptor instead.
func (*NodeFailure) Descriptor() ([]byte, []int) {
	return file_controlplane_events_node_events_proto_rawDescGZIP(), []int{0}
}

// Apply latency to every request
type NetworkLatency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatencyMsec int32 `protobuf:"varint,1,opt,name=latency_msec,json=latencyMsec,proto3" json:"latency_msec,omitempty"`
}

func (x *NetworkLatency) Reset() {
	*x = NetworkLatency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_events_node_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkLatency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkLatency) ProtoMessage() {}

func (x *NetworkLatency) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_events_node_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkLatency.ProtoReflect.Descriptor instead.
func (*NetworkLatency) Descriptor() ([]byte, []int) {
	return file_controlplane_events_node_events_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkLatency) GetLatencyMsec() int32 {
	if x != nil {
		return x.LatencyMsec
	}
	return 0
}

// We apply timeout to every request from k8s besides the ping / heartbeat
type TimeoutKeepHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TimeoutKeepHeartbeat) Reset() {
	*x = TimeoutKeepHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_events_node_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutKeepHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutKeepHeartbeat) ProtoMessage() {}

func (x *TimeoutKeepHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_events_node_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutKeepHeartbeat.ProtoReflect.Descriptor instead.
func (*TimeoutKeepHeartbeat) Descriptor() ([]byte, []int) {
	return file_controlplane_events_node_events_proto_rawDescGZIP(), []int{2}
}

// We only apply timeout to ping / heartbeat
type NoTimeoutNoHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoTimeoutNoHeartbeat) Reset() {
	*x = NoTimeoutNoHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_events_node_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoTimeoutNoHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoTimeoutNoHeartbeat) ProtoMessage() {}

func (x *NoTimeoutNoHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_events_node_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoTimeoutNoHeartbeat.ProtoReflect.Descriptor instead.
func (*NoTimeoutNoHeartbeat) Descriptor() ([]byte, []int) {
	return file_controlplane_events_node_events_proto_rawDescGZIP(), []int{3}
}

// Apply resource pressure to this node
type ResourcePressure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The percentage of CPU used
	CpuUsage int32 `protobuf:"varint,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// The percentage of memory used
	MemoryUsage int32 `protobuf:"varint,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	// The percentage of storage used
	StorageUsage int32 `protobuf:"varint,3,opt,name=storage_usage,json=storageUsage,proto3" json:"storage_usage,omitempty"`
	// The percentage of ephermal storage used
	EphemeralStorageUsage int32 `protobuf:"varint,4,opt,name=ephemeral_storage_usage,json=ephemeralStorageUsage,proto3" json:"ephemeral_storage_usage,omitempty"`
}

func (x *ResourcePressure) Reset() {
	*x = ResourcePressure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_events_node_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourcePressure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcePressure) ProtoMessage() {}

func (x *ResourcePressure) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_events_node_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcePressure.ProtoReflect.Descriptor instead.
func (*ResourcePressure) Descriptor() ([]byte, []int) {
	return file_controlplane_events_node_events_proto_rawDescGZIP(), []int{4}
}

func (x *ResourcePressure) GetCpuUsage() int32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ResourcePressure) GetMemoryUsage() int32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ResourcePressure) GetStorageUsage() int32 {
	if x != nil {
		return x.StorageUsage
	}
	return 0
}

func (x *ResourcePressure) GetEphemeralStorageUsage() int32 {
	if x != nil {
		return x.EphemeralStorageUsage
	}
	return 0
}

var File_controlplane_events_node_events_proto protoreflect.FileDescriptor

var file_controlplane_events_node_events_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x61, 0x74, 0x65, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x4e,
	0x6f, 0x64, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x22, 0x33, 0x0a, 0x0e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x21, 0x0a, 0x0c,
	0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6d, 0x73, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x73, 0x65, 0x63, 0x22,
	0x16, 0x0a, 0x14, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x4e, 0x6f, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x4e, 0x6f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x22,
	0xaf, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x65, 0x73,
	0x73, 0x75, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70, 0x75, 0x5f, 0x75, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x65, 0x70, 0x68,
	0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x75,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x65, 0x70, 0x68, 0x65,
	0x6d, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x74, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x2d, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x64, 0x63, 0x2d, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x2d,
	0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_controlplane_events_node_events_proto_rawDescOnce sync.Once
	file_controlplane_events_node_events_proto_rawDescData = file_controlplane_events_node_events_proto_rawDesc
)

func file_controlplane_events_node_events_proto_rawDescGZIP() []byte {
	file_controlplane_events_node_events_proto_rawDescOnce.Do(func() {
		file_controlplane_events_node_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_controlplane_events_node_events_proto_rawDescData)
	})
	return file_controlplane_events_node_events_proto_rawDescData
}

var file_controlplane_events_node_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_controlplane_events_node_events_proto_goTypes = []interface{}{
	(*NodeFailure)(nil),          // 0: apate.controlplane.NodeFailure
	(*NetworkLatency)(nil),       // 1: apate.controlplane.NetworkLatency
	(*TimeoutKeepHeartbeat)(nil), // 2: apate.controlplane.TimeoutKeepHeartbeat
	(*NoTimeoutNoHeartbeat)(nil), // 3: apate.controlplane.NoTimeoutNoHeartbeat
	(*ResourcePressure)(nil),     // 4: apate.controlplane.ResourcePressure
}
var file_controlplane_events_node_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_controlplane_events_node_events_proto_init() }
func file_controlplane_events_node_events_proto_init() {
	if File_controlplane_events_node_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controlplane_events_node_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controlplane_events_node_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkLatency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controlplane_events_node_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeoutKeepHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controlplane_events_node_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoTimeoutNoHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controlplane_events_node_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourcePressure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controlplane_events_node_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_events_node_events_proto_goTypes,
		DependencyIndexes: file_controlplane_events_node_events_proto_depIdxs,
		MessageInfos:      file_controlplane_events_node_events_proto_msgTypes,
	}.Build()
	File_controlplane_events_node_events_proto = out.File
	file_controlplane_events_node_events_proto_rawDesc = nil
	file_controlplane_events_node_events_proto_goTypes = nil
	file_controlplane_events_node_events_proto_depIdxs = nil
}
