// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: controlplane/events/pod_events.proto

package events

import (
	scenario "github.com/atlarge-research/opendc-emulate-kubernetes/api/scenario"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PodStatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewStatus scenario.PodStatus `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=apate.scenario.PodStatus" json:"new_status,omitempty"`
}

func (x *PodStatusUpdate) Reset() {
	*x = PodStatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_events_pod_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatusUpdate) ProtoMessage() {}

func (x *PodStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_events_pod_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatusUpdate.ProtoReflect.Descriptor instead.
func (*PodStatusUpdate) Descriptor() ([]byte, []int) {
	return file_controlplane_events_pod_events_proto_rawDescGZIP(), []int{0}
}

func (x *PodStatusUpdate) GetNewStatus() scenario.PodStatus {
	if x != nil {
		return x.NewStatus
	}
	return scenario.PodStatus_POD_PENDING
}

type PodStartTimeUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewStartTime string `protobuf:"bytes,1,opt,name=new_start_time,json=newStartTime,proto3" json:"new_start_time,omitempty"`
}

func (x *PodStartTimeUpdate) Reset() {
	*x = PodStartTimeUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controlplane_events_pod_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodStartTimeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStartTimeUpdate) ProtoMessage() {}

func (x *PodStartTimeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_events_pod_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStartTimeUpdate.ProtoReflect.Descriptor instead.
func (*PodStartTimeUpdate) Descriptor() ([]byte, []int) {
	return file_controlplane_events_pod_events_proto_rawDescGZIP(), []int{1}
}

func (x *PodStartTimeUpdate) GetNewStartTime() string {
	if x != nil {
		return x.NewStartTime
	}
	return ""
}

var File_controlplane_events_pod_events_proto protoreflect.FileDescriptor

var file_controlplane_events_pod_events_proto_rawDesc = []byte{
	0x0a, 0x24, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x6f, 0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x61, 0x70, 0x61, 0x74, 0x65, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x1a, 0x13, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2f, 0x70, 0x6f, 0x64, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0f, 0x50, 0x6f, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x6e, 0x65, 0x77,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x61, 0x70, 0x61, 0x74, 0x65, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x50,
	0x6f, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x3a, 0x0a, 0x12, 0x50, 0x6f, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x65, 0x77,
	0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x42,
	0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x74,
	0x6c, 0x61, 0x72, 0x67, 0x65, 0x2d, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x6f,
	0x70, 0x65, 0x6e, 0x64, 0x63, 0x2d, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x2d, 0x6b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_controlplane_events_pod_events_proto_rawDescOnce sync.Once
	file_controlplane_events_pod_events_proto_rawDescData = file_controlplane_events_pod_events_proto_rawDesc
)

func file_controlplane_events_pod_events_proto_rawDescGZIP() []byte {
	file_controlplane_events_pod_events_proto_rawDescOnce.Do(func() {
		file_controlplane_events_pod_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_controlplane_events_pod_events_proto_rawDescData)
	})
	return file_controlplane_events_pod_events_proto_rawDescData
}

var file_controlplane_events_pod_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_controlplane_events_pod_events_proto_goTypes = []interface{}{
	(*PodStatusUpdate)(nil),    // 0: apate.controlplane.events.PodStatusUpdate
	(*PodStartTimeUpdate)(nil), // 1: apate.controlplane.events.PodStartTimeUpdate
	(scenario.PodStatus)(0),    // 2: apate.scenario.PodStatus
}
var file_controlplane_events_pod_events_proto_depIdxs = []int32{
	2, // 0: apate.controlplane.events.PodStatusUpdate.new_status:type_name -> apate.scenario.PodStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_controlplane_events_pod_events_proto_init() }
func file_controlplane_events_pod_events_proto_init() {
	if File_controlplane_events_pod_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controlplane_events_pod_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodStatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controlplane_events_pod_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodStartTimeUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controlplane_events_pod_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_events_pod_events_proto_goTypes,
		DependencyIndexes: file_controlplane_events_pod_events_proto_depIdxs,
		MessageInfos:      file_controlplane_events_pod_events_proto_msgTypes,
	}.Build()
	File_controlplane_events_pod_events_proto = out.File
	file_controlplane_events_pod_events_proto_rawDesc = nil
	file_controlplane_events_pod_events_proto_goTypes = nil
	file_controlplane_events_pod_events_proto_depIdxs = nil
}
