// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/atlarge-research/opendc-emulate-kubernetes/pkg/run (interfaces: ApateletRunner)

// Package mock_run is a generated GoMock package.
package mock_run

import (
	context "context"
	env "github.com/atlarge-research/opendc-emulate-kubernetes/pkg/env"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockApateletRunner is a mock of ApateletRunner interface
type MockApateletRunner struct {
	ctrl     *gomock.Controller
	recorder *MockApateletRunnerMockRecorder
}

// MockApateletRunnerMockRecorder is the mock recorder for MockApateletRunner
type MockApateletRunnerMockRecorder struct {
	mock *MockApateletRunner
}

// NewMockApateletRunner creates a new mock instance
func NewMockApateletRunner(ctrl *gomock.Controller) *MockApateletRunner {
	mock := &MockApateletRunner{ctrl: ctrl}
	mock.recorder = &MockApateletRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockApateletRunner) EXPECT() *MockApateletRunnerMockRecorder {
	return m.recorder
}

// SpawnApatelets mocks base method
func (m *MockApateletRunner) SpawnApatelets(arg0 context.Context, arg1 int, arg2 env.ApateletEnvironment, arg3 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SpawnApatelets", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SpawnApatelets indicates an expected call of SpawnApatelets
func (mr *MockApateletRunnerMockRecorder) SpawnApatelets(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnApatelets", reflect.TypeOf((*MockApateletRunner)(nil).SpawnApatelets), varargs...)
}
