kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
    apiServerAddress: "0.0.0.0"

# add to the apiServer certSANs the name of the docker (dind) service in order to be able to reach the cluster through it
# see https://github.com/kind-ci/examples/blob/master/gitlab/kind-config.yaml
kubeadmConfigPatchesJSON6902:
    - group: kubeadm.k8s.io
      version: v1beta2
      kind: ClusterConfiguration
      patch: |
          - op: add
            path: /apiServer/certSANs/-
            value: docker
