---
nodeExporter:
  enabled: false
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      -
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        job_name: apatelet-node
        kubernetes_sd_configs:
          -
            role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_labelpresent_emulated]
            regex: '^$'
            action: drop
          -
            action: replace
            regex: (.*)
            replacement: "${1}"
            separator: ;
            source_labels:
              - __meta_kubernetes_node_name
            target_label: node
          -
            action: replace
            regex: (.*)
            replacement: "${1}"
            separator: ;
            source_labels:
              - __meta_kubernetes_node_label_metrics_port
            target_label: metrics_port
          -
            source_labels: [__address__, __meta_kubernetes_node_label_metrics_port]
            separator:     ';'
            regex: '^(.*?)(:.*)?;(.*)$'
            target_label: __address__
            action: replace
            replacement: ${1}:${3}
        scheme: http
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
