apiVersion: apate.opendc.org/v1
kind: NodeConfiguration
metadata:
    name: test-deployment1
spec:
    replicas: 3001
    resources:
        memory: 5G
        cpu: 1000
        storage: 5T
        ephemeral_storage: 120G
        max_pods: 150
    tasks:
        - timestamp: 10s
          state:
              node_failed: true
              network_latency: 10ms
