apiVersion: apate.opendc.org/v1
kind: NodeConfiguration
metadata:
    name: test-deployment1
spec:
    replicas: 1
    resources:
        memory: 5G
        cpu: 5000
        storage: 5T
        ephemeral_storage: 120G
        max_pods: 150
    tasks:
        - timestamp: 1s
          state:
              node_failed: true
