apiVersion: apate.opendc.org/v1
kind: PodConfiguration
metadata:
    name: crd-deployment
spec:
    tasks:
        - timestamp: 1s
          state:
              pod_resources:
                  cpu: 1000