apiVersion: apate.opendc.org/v1
kind: PodConfiguration
metadata:
    name: crd-deployment
spec:
    pod_resources:
        memory: 1G
    tasks:
        -   timestamp: 1m
            relative_to_pod: true
            state:
                create_pod_response: ERROR

