generate:
  stage: build
  before_script:
    - go mod download
  script:
    - make crd_gen mock_gen
    # Had to add -I /go/pkg/mod/github.com/gogo/protobuf@v1.2.1/protobuf/ in order to make it work
    - protoc -I ./api -I $GOPATH/pkg/mod/github.com/gogo/protobuf@v1.2.1/protobuf/ --go_opt=paths=source_relative --go_out=plugins=grpc:./api/ `find ./api/ -type f -name "*.proto" -print`

build:
  stage: build
  before_script:
    - go mod download
  script:
    - go install ./...

build apatelet:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -f services/apatelet/Dockerfile -t $VK_IMAGE .
    - docker push "$VK_IMAGE"

build cp:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -f services/controlplane/Dockerfile -t $CP_IMAGE .
    - docker push "$CP_IMAGE"