// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorStats) DeepCopyInto(out *AcceleratorStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorStats.
func (in *AcceleratorStats) DeepCopy() *AcceleratorStats {
	if in == nil {
		return nil
	}
	out := new(AcceleratorStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUStats) DeepCopyInto(out *CPUStats) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.UsageNanoCores != nil {
		in, out := &in.UsageNanoCores, &out.UsageNanoCores
		*out = new(uint64)
		**out = **in
	}
	if in.UsageCoreNanoSeconds != nil {
		in, out := &in.UsageCoreNanoSeconds, &out.UsageCoreNanoSeconds
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUStats.
func (in *CPUStats) DeepCopy() *CPUStats {
	if in == nil {
		return nil
	}
	out := new(CPUStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerStats) DeepCopyInto(out *ContainerStats) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(CPUStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemoryStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Accelerators != nil {
		in, out := &in.Accelerators, &out.Accelerators
		*out = make([]AcceleratorStats, len(*in))
		copy(*out, *in)
	}
	if in.Rootfs != nil {
		in, out := &in.Rootfs, &out.Rootfs
		*out = new(FsStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(FsStats)
		(*in).DeepCopyInto(*out)
	}
	if in.UserDefinedMetrics != nil {
		in, out := &in.UserDefinedMetrics, &out.UserDefinedMetrics
		*out = make([]UserDefinedMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerStats.
func (in *ContainerStats) DeepCopy() *ContainerStats {
	if in == nil {
		return nil
	}
	out := new(ContainerStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmulatedPod) DeepCopyInto(out *EmulatedPod) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmulatedPod.
func (in *EmulatedPod) DeepCopy() *EmulatedPod {
	if in == nil {
		return nil
	}
	out := new(EmulatedPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmulatedPod) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmulatedPodList) DeepCopyInto(out *EmulatedPodList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EmulatedPod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmulatedPodList.
func (in *EmulatedPodList) DeepCopy() *EmulatedPodList {
	if in == nil {
		return nil
	}
	out := new(EmulatedPodList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmulatedPodList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmulatedPodSpec) DeepCopyInto(out *EmulatedPodSpec) {
	*out = *in
	in.DirectState.DeepCopyInto(&out.DirectState)
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]EmulatedPodTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmulatedPodSpec.
func (in *EmulatedPodSpec) DeepCopy() *EmulatedPodSpec {
	if in == nil {
		return nil
	}
	out := new(EmulatedPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmulatedPodState) DeepCopyInto(out *EmulatedPodState) {
	*out = *in
	if in.PodResources != nil {
		in, out := &in.PodResources, &out.PodResources
		*out = new(PodStats)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmulatedPodState.
func (in *EmulatedPodState) DeepCopy() *EmulatedPodState {
	if in == nil {
		return nil
	}
	out := new(EmulatedPodState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmulatedPodTask) DeepCopyInto(out *EmulatedPodTask) {
	*out = *in
	in.State.DeepCopyInto(&out.State)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmulatedPodTask.
func (in *EmulatedPodTask) DeepCopy() *EmulatedPodTask {
	if in == nil {
		return nil
	}
	out := new(EmulatedPodTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FsStats) DeepCopyInto(out *FsStats) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.AvailableBytes != nil {
		in, out := &in.AvailableBytes, &out.AvailableBytes
		*out = new(uint64)
		**out = **in
	}
	if in.CapacityBytes != nil {
		in, out := &in.CapacityBytes, &out.CapacityBytes
		*out = new(uint64)
		**out = **in
	}
	if in.UsedBytes != nil {
		in, out := &in.UsedBytes, &out.UsedBytes
		*out = new(uint64)
		**out = **in
	}
	if in.InodesFree != nil {
		in, out := &in.InodesFree, &out.InodesFree
		*out = new(uint64)
		**out = **in
	}
	if in.Inodes != nil {
		in, out := &in.Inodes, &out.Inodes
		*out = new(uint64)
		**out = **in
	}
	if in.InodesUsed != nil {
		in, out := &in.InodesUsed, &out.InodesUsed
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FsStats.
func (in *FsStats) DeepCopy() *FsStats {
	if in == nil {
		return nil
	}
	out := new(FsStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceStats) DeepCopyInto(out *InterfaceStats) {
	*out = *in
	if in.RxBytes != nil {
		in, out := &in.RxBytes, &out.RxBytes
		*out = new(uint64)
		**out = **in
	}
	if in.RxErrors != nil {
		in, out := &in.RxErrors, &out.RxErrors
		*out = new(uint64)
		**out = **in
	}
	if in.TxBytes != nil {
		in, out := &in.TxBytes, &out.TxBytes
		*out = new(uint64)
		**out = **in
	}
	if in.TxErrors != nil {
		in, out := &in.TxErrors, &out.TxErrors
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceStats.
func (in *InterfaceStats) DeepCopy() *InterfaceStats {
	if in == nil {
		return nil
	}
	out := new(InterfaceStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStats) DeepCopyInto(out *MemoryStats) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.AvailableBytes != nil {
		in, out := &in.AvailableBytes, &out.AvailableBytes
		*out = new(uint64)
		**out = **in
	}
	if in.UsageBytes != nil {
		in, out := &in.UsageBytes, &out.UsageBytes
		*out = new(uint64)
		**out = **in
	}
	if in.WorkingSetBytes != nil {
		in, out := &in.WorkingSetBytes, &out.WorkingSetBytes
		*out = new(uint64)
		**out = **in
	}
	if in.RSSBytes != nil {
		in, out := &in.RSSBytes, &out.RSSBytes
		*out = new(uint64)
		**out = **in
	}
	if in.PageFaults != nil {
		in, out := &in.PageFaults, &out.PageFaults
		*out = new(uint64)
		**out = **in
	}
	if in.MajorPageFaults != nil {
		in, out := &in.MajorPageFaults, &out.MajorPageFaults
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStats.
func (in *MemoryStats) DeepCopy() *MemoryStats {
	if in == nil {
		return nil
	}
	out := new(MemoryStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStats) DeepCopyInto(out *NetworkStats) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	in.InterfaceStats.DeepCopyInto(&out.InterfaceStats)
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]InterfaceStats, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStats.
func (in *NetworkStats) DeepCopy() *NetworkStats {
	if in == nil {
		return nil
	}
	out := new(NetworkStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStats) DeepCopyInto(out *NodeStats) {
	*out = *in
	if in.SystemContainers != nil {
		in, out := &in.SystemContainers, &out.SystemContainers
		*out = make([]ContainerStats, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(CPUStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemoryStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Fs != nil {
		in, out := &in.Fs, &out.Fs
		*out = new(FsStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(RuntimeStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Rlimit != nil {
		in, out := &in.Rlimit, &out.Rlimit
		*out = new(RlimitStats)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStats.
func (in *NodeStats) DeepCopy() *NodeStats {
	if in == nil {
		return nil
	}
	out := new(NodeStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCReference) DeepCopyInto(out *PVCReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCReference.
func (in *PVCReference) DeepCopy() *PVCReference {
	if in == nil {
		return nil
	}
	out := new(PVCReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodReference) DeepCopyInto(out *PodReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodReference.
func (in *PodReference) DeepCopy() *PodReference {
	if in == nil {
		return nil
	}
	out := new(PodReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodStats) DeepCopyInto(out *PodStats) {
	*out = *in
	out.PodRef = in.PodRef
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerStats, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(CPUStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemoryStats)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkStats)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeStats != nil {
		in, out := &in.VolumeStats, &out.VolumeStats
		*out = make([]VolumeStats, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EphemeralStorage != nil {
		in, out := &in.EphemeralStorage, &out.EphemeralStorage
		*out = new(FsStats)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodStats.
func (in *PodStats) DeepCopy() *PodStats {
	if in == nil {
		return nil
	}
	out := new(PodStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RlimitStats) DeepCopyInto(out *RlimitStats) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.MaxPID != nil {
		in, out := &in.MaxPID, &out.MaxPID
		*out = new(int64)
		**out = **in
	}
	if in.NumOfRunningProcesses != nil {
		in, out := &in.NumOfRunningProcesses, &out.NumOfRunningProcesses
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RlimitStats.
func (in *RlimitStats) DeepCopy() *RlimitStats {
	if in == nil {
		return nil
	}
	out := new(RlimitStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeStats) DeepCopyInto(out *RuntimeStats) {
	*out = *in
	if in.ImageFs != nil {
		in, out := &in.ImageFs, &out.ImageFs
		*out = new(FsStats)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeStats.
func (in *RuntimeStats) DeepCopy() *RuntimeStats {
	if in == nil {
		return nil
	}
	out := new(RuntimeStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Summary) DeepCopyInto(out *Summary) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]PodStats, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Summary.
func (in *Summary) DeepCopy() *Summary {
	if in == nil {
		return nil
	}
	out := new(Summary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedMetric) DeepCopyInto(out *UserDefinedMetric) {
	*out = *in
	in.UserDefinedMetricDescriptor.DeepCopyInto(&out.UserDefinedMetricDescriptor)
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedMetric.
func (in *UserDefinedMetric) DeepCopy() *UserDefinedMetric {
	if in == nil {
		return nil
	}
	out := new(UserDefinedMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedMetricDescriptor) DeepCopyInto(out *UserDefinedMetricDescriptor) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedMetricDescriptor.
func (in *UserDefinedMetricDescriptor) DeepCopy() *UserDefinedMetricDescriptor {
	if in == nil {
		return nil
	}
	out := new(UserDefinedMetricDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStats) DeepCopyInto(out *VolumeStats) {
	*out = *in
	in.FsStats.DeepCopyInto(&out.FsStats)
	if in.PVCRef != nil {
		in, out := &in.PVCRef, &out.PVCRef
		*out = new(PVCReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStats.
func (in *VolumeStats) DeepCopy() *VolumeStats {
	if in == nil {
		return nil
	}
	out := new(VolumeStats)
	in.DeepCopyInto(out)
	return out
}
